### ISSUE TITLE
Make application window remember it's size after exiting the app

### ISSUE THREAD

**Issue by youngLights14** [mjakeman/extension-manager#102]
Application (version 0.2.2) doesn't remember it's size after reopening.

**Comment by mjakeman** [comment]
Do GNOME apps normally do this?

I'm not opposed to it in principle, but it seems a bit odd to me. Normally I'd expect reopening an app to restore it to the "default" state. Is there a specific reason why you'd want this behaviour?

Looking at https://developer.gnome.org/hig/patterns/containers/windows.html:
> The default size of primary windows should be appropriate to their content. Windows that display large content like documents or videos should be big enough to support viewing and editing without the need to increase the window size. On the other hand, windows with a limited amount of UI can and should default to a smaller size, in order to avoid large amounts of blank space.

**Comment by mjakeman** [comment]
> I understand if you don't want to implement saving windows size, but at least remembering previous window position would be great.

Unfortunately the reality is much of the opposite. Saving window dimensions is straightforward to do (https://wiki.gnome.org/HowDoI/SaveWindowState).

For position however, under Wayland, it is impossible to position the window at a specific place on screen. I believe this is done for security reasons (and is probably for the best given how messy X11 was). This sort of thing would need to be implemented by the compositor - looks like there's some progress with GNOME supporting it. If that gets implemented, then I'm happy to do the relevant bits here.

Some interesting links:
 - https://gitlab.gnome.org/GNOME/mutter/-/issues/417
 - https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3655
 - https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/18
 - https://tecnocode.co.uk/2021/12/08/state-persistence-for-apps-and-sessions-endless-orange-week/

**Comment by mjakeman** [comment]
Going to close this as it seems GNOME is moving away from this trend. If anything changes I'm happy to implement

**Comment by nekohayo** [comment]
Clarification: GNOME is not moving away from this trend, most (if not all) apps remember their window size. The "size appropriately by default" principle comes _before_ the "remember sizes/physical properties" principle, but only "for the 1st run"; remembering the size then supplants it for subsequent runs. This has been true since  GNOME 2 and remains true to this day. Unless you just maximize automatically calculate the height of the window each time, which would amount to vertically maximizing it all the time because it'll inevitably scroll when it has a bunch of items in it.

Example of applications honoring the "decent default size on 1st run, then remember the user-set size" principle: Nautilus, Epiphany, Calendar, Console, Prompt, Gedit, Text Editor, Tuba, Monophony, Shortwave, System Monitor, Gitg, Meld, GNote, etc.

As such, I would suggest reopening this; I was about to report the same issue :)

**Comment by oscfdezdz** [comment]
I also noticed that Extensions app has [recently added it](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3115) and it will be available for the next release. This issue is worth revisiting.
