### ISSUE TITLE
Additional Repositories

### ISSUE THREAD

**Issue by trymeouteh** [mjakeman/extension-manager#109]
To make GNOME extensions more decentralised, maybe creating a way to self host your own GNOME extensions repository and be able to add it into the extension manager.

**Comment by mjakeman** [comment]
I'm not sure how useful this would be given nobody has tried hosting their own extensions repo (afaik).

That being said, it's very possible - All you'd need to do is host an instance of https://gitlab.gnome.org/Infrastructure/extensions-web/ and point extension manager at it instead of extensions.gnome.org.

It could be worth adding a settings key for changing the target server. I imagine that might be useful when e.g. working on extensions-web locally.

---

I'll leave this open for anyone interested. Comment below if you'd like to work on this.

I imagine the steps involved would be:
 - Refactor out all hardcoded references to extensions.gnome.org
 - Add a GSettings key for target web address
 - (optionally) Implement a GUI for changing the target web server

**Comment by mjakeman** [comment]
I'm going to close this since there are no actual alternatives to EGO as far as I can tell. If someone really wants this, patches are welcome!

**Comment by trymeouteh** [comment]
> It could be worth adding a settings key for changing the target server. I imagine that might be useful when e.g. working on extensions-web locally.

Would be great to have a setting to add and remove instances within Extension Manager. And when your searching for extensions, you can choose which instance to search and install extensions from.
