### ISSUE TITLE
Add swipe gesture to go out of the Details view 

### ISSUE THREAD

**Issue by musiclover382** [mjakeman/extension-manager#161]
Not really important but I use a trackpad and every time I view an extension's details I have to go all the way up-left to exit and it's kinda annoying, expecially when casually browsing through extensions.

A swipe gesture would be perfect

**Comment by mjakeman** [comment]
The `AdwLeaflet` widget we use for the main view is already set-up to use a swipe gesture to exit.

Unfortunately, there's a [bug in GTK 4 (and thus libadwaita)](https://gitlab.gnome.org/GNOME/libadwaita/-/issues/16) which prevents starting a touchpad swipe from within a scrolled window. This doesn't affect touch, so if you have a touch screen the swipe will work.

Once this gets fixed in GTK, we should get it "for free", so hopefully that will be resolved soon.

**Comment by mjakeman** [comment]
Let's close this as it isn't actionable - hopefully GTK will support this soon.
