### ISSUE TITLE
Direct link to extension's website

### ISSUE THREAD

**Issue by bordam** [mjakeman/extension-manager#162]
You're probably already aware of this, anyway:

In the official Extensions app you can directly open an extension's website clicking a button in the bottom-left of an open extension entry.

Maybe you could add a button to open the extension's website in the Detailes view, under the View on Extensions button?

**Comment by mjakeman** [comment]
This was originally part of https://github.com/mjakeman/extension-manager/pull/100 but I couldn't figure out how to actually get the homepage URL.

Currently, due to the requirement for the application to work offline, the installed page data is populated from GNOME Shell over DBus while the details and browse pages are populated from [EGO](extensions.gnome.org/) over the network. Unfortunately it looks like EGO does not provide us with the extension URL (this is only available over DBus, hence why the extensions app can access it).

In order to get this to work reliably, we'll likely need some form of API for it on the EGO-side of things. Definitely something I'd like to have, but not the easiest to implement right now.
