### ISSUE TITLE
Extension name needs to be HTML-escaped on the "Installed" page

### ISSUE THREAD

**Issue by guihkx** [mjakeman/extension-manager#173]
The extension "**Sound Input & Output Device Chooser**" is not being properly displayed on the "Installed" page (title is empty):

![image](https://user-images.githubusercontent.com/626206/163080249-2bfbc830-3deb-4dce-8fbd-86a5ff61e267.png)

And the journal shows this warning:

>**Failed to set text 'Sound Input & Output Device Chooser' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;**

At the same time, the extension name look correct on the "Browse" page:

![image](https://user-images.githubusercontent.com/626206/163080438-8235d8b7-578b-44b4-8f06-da8d221f2029.png)

- **OS:** Arch Linux
- **Version:** 0.3.0

**Comment by gabrbrand** [comment]
I have the same issue on Fedora 35.
In addition to that the versions of all System Extensions are not displayed.
![extension-manager_bug2](https://user-images.githubusercontent.com/98428543/163360939-cdb3c2ac-5e80-4b24-806e-0361775044bb.png)

**Comment by mjakeman** [comment]
Yeah, I can reproduce this too. Not sure how it slipped through.

> @gabrbrand:  In addition to that the versions of all System Extensions are not displayed.

The system extensions not having a version is a separate (and expected) issue. Since the version exists primarily for GNOME Shell's internal extension management (ensuring version compatibility, etc), it is hit-or-miss whether extensions provided through distro repositories will have one. 

The idea is that extensions from distro repositories will always work since they can be pinned against a specific version of Shell. Feel free to open an issue for the empty row if you'd like.
