### ISSUE TITLE
Add "Upgrade Assistant"

### ISSUE THREAD

**Issue by mjakeman** [mjakeman/extension-manager#183]
A frequent criticism I see is that every time a new version of GNOME comes out it causes extensions to break. Most extensions will be updated in due course, but these can lag behind by a few months. So if someone heavily relies on a certain extension for their workflow, they can be in for an unpleasant surprise. 

Through EGO, we can already retrieve a list of supported versions for each extension, so it wouldn't be a stretch to allow users to see extension compatibility for a given version of GNOME.

I imagine this taking the form of a menu entry titled "Upgrade Assistant" which opens a new dialog displaying which extensions (of those the user currently has installed/enabled) would stop working upon upgrading to the 'n + 1' version.

In a perfect world, this would be integrated into GNOME Software/Settings/wherever the upgrade take place, but adding it here seems like a healthy first step.

**Comment by johns2s** [comment]
This might be _way_ out of scope of this app, but in the spirit of first steps, I'll leave it here:

Since in my experience extensions generally work fine under new versions, It would be really cool if users could disable version checking from within Extension Manager, then mark any extensions that work fine as 'working'. If a set threshold (and/or ratio) of users mark it as working, a PR is filed against the upstream repo to add said version.

**Comment by mjakeman** [comment]
Very much out of scope I'm afraid :)

With the first point, we can't actually enable/disable GNOME Shell's version checking from inside Extension Manager because flatpak does not let us access system settings (rightfully so).

The second part would actually be easier but the overhead of running a server to track reports isn't something I'm interested in doing. I would worry about false reports as errors can occur at any point through the extension's lifecycle, not just at startup.
