### ISSUE TITLE
Application not starting if using Nvidia drivers on Wayland

### ISSUE THREAD

**Issue by simoneobo** [mjakeman/extension-manager#184]
Hi, i'm using Ubuntu 22.04 (fresh install) with closed source Nvidia 510 drivers and Wayland session.

Applications fails to open with the following error:
`Gdk-Message: 23:33:06.474: Error 71 (Protocol error) dispatching to Wayland display.`

The only way i found to start it, it's using the following variables:
`GSK_RENDERER=cairo extension-manager `

Thanks

**Comment by moh-slimani** [comment]
i have the same problem

**Comment by mjakeman** [comment]
Hi, could you specify whether you have installed extension-manager via flatpak or the Ubuntu repos? Also, are the 510 drivers the ones that support Wayland out-of-the-box?

Since running GTK 4 with the `cairo` backend works, this is going to be an issue with hardware acceleration. We don't do anything special in extension manager so it'll likely be a problem with the driver itself. Something to note is that flatpak does not use the host drivers - so if you are using flatpak, try installing from the Ubuntu repos instead.

Unfortunately I have no way to reproduce/test this as I don't own any Nvidia hardware.

**Comment by breenkevp** [comment]
I can verify it works for me via flatpak and the 510 drivers on wayland. Running Fedora 35 if that makes a difference.

**Comment by Win-Lawson** [comment]
> I can verify it works for me via flatpak and the 510 drivers on wayland. Running Fedora 35 if that makes a difference.

I can confirm that the extension manager application opens on flatpak, however it is not possible to open settings for individual extensions. Is this the case for you too?

**Comment by voidiums** [comment]
App fails to open here as well.
Nvidia 1050ti with closed source 510 driver on fedora 36 Wayland using the flatpak version as it's the only option available.

**Comment by mjakeman** [comment]
I wonder if this is specifically an extension manager issue, or if it generally affects gtk4/libadwaita apps. To narrow it down, could you try a few of the following apps (from flathub) and see if they can run under Nvidia drivers?
 - [Kooha](https://flathub.org/apps/details/io.github.seadve.Kooha)
 - [GNOME Text Editor](https://flathub.org/apps/details/org.gnome.TextEditor)
 - [rnote](https://flathub.org/apps/details/com.github.flxzt.rnote)
 - [Fragments](https://flathub.org/apps/details/de.haeckerfelix.Fragments)

**Comment by voidiums** [comment]
> I wonder if this is specifically an extension manager issue, or if it generally affects gtk4/libadwaita apps. To narrow it down, could you try a few of the following apps (from flathub) and see if they can run under Nvidia drivers?
> 
>     * [Kooha](https://flathub.org/apps/details/io.github.seadve.Kooha)
> 
>     * [GNOME Text Editor](https://flathub.org/apps/details/org.gnome.TextEditor)
> 
>     * [rnote](https://flathub.org/apps/details/com.github.flxzt.rnote)
> 
>     * [Fragments](https://flathub.org/apps/details/de.haeckerfelix.Fragments)

All 4 apps do NOT open under wayland.

Other apps I tested and do NOT open:
- Pitivi 2021.05
- Solanum 3.0.1
- Clapper 0.4.1
- Amberol 0.6.3

I found some Flatpak apps that DO open under wayland (mostly older GTK2/GTK3 or QT apps):
- GIMP 2.10.30
- Inkscape 1.2
- Audacity 3.1.3
- Krita 5.0.6
- Kdenlive 22.04.1

**Comment by mjakeman** [comment]
Is this still an issue as of the latest Nvidia drivers?

**Comment by simoneobo** [comment]
Hi, i confirm that with Nvidia drivers 510.85.02 the problem is gone!

**Comment by mjakeman** [comment]
Great!

**Comment by vishnup95** [comment]
Running nvidia-driver version 525 with Wayland on Ubuntu 22.04 seems to create the same issue. The `GSK_RENDERER` env variable works. 

PS: I have the app installed via apt and I am still on `v0.3.0`. 
@mjakeman why does changing the gnome-extension renderer make this work though?

**Comment by mjakeman** [comment]
@vishnup95 Does this affect other GTK/libadwaita apps or just extension manager?

0.3.0 shouldn't make a difference in theory, the only change is 0.4 uses newer versions of the GTK libraries.

For `GSK_RENDERER=cairo`, it overrides the way GTK draws to the screen and uses (slower) CPU rendering instead. Since the issue is with Nvidia drivers, rendering with cairo bypasses them entirely and allows the program to run. Ideally we want to use the drivers though, because it's several orders of magnitude faster to run it on the GPU.

This isn't something we can fix in extension-manager, your best bet is to file an issue against Ubuntu (or upgrade to 22.10 - that could work?)

**Comment by vishnup95** [comment]
> @vishnup95 Does this affect other GTK/libadwaita apps or just extension manager?
> 
> 0.3.0 shouldn't make a difference in theory, the only change is 0.4 uses newer versions of the GTK libraries.
> 
> For `GSK_RENDERER=cairo`, it overrides the way GTK draws to the screen and uses (slower) CPU rendering instead. Since the issue is with Nvidia drivers, rendering with cairo bypasses them entirely and allows the program to run. Ideally we want to use the drivers though, because it's several orders of magnitude faster to run it on the GPU.
> 
> This isn't something we can fix in extension-manager, your best bet is to file an issue against Ubuntu (or upgrade to 22.10 - that could work?)

Thanks for the reply. 
Don't really have a lot of a GTK apps I know of that I use daily. I have gnome-music which I believe is a GTK app and that works. If you want me to try something particular I am more than happy to. 
Not really looking to update to 22.10. I am okay with the workaround for now. Should I try the flatpak version? Will that make any difference since it's sand-boxed environment. I don't really have a great understanding of how Linux software runs, so apologies if it's a senseless question.  (?)
