### ISSUE TITLE
Add update without log out

### ISSUE THREAD

**Issue by psydvl** [mjakeman/extension-manager#189]
For now, you are asking to log out from GNOME to install a new version of extensions.
However, I can update from https://extensions.gnome.org/local/ without logging out or something else.

**Comment by mjakeman** [comment]
Hi, thanks for the report.

From what I understand, the reason GNOME Shell now prompts a restart for updates is due to issues with hotswapping extension versions while they are running. While extensions (theoretically) should clean up all resources after being unloaded, this isn't guaranteed and updating the version on the fly can lead to system instability.

On a technical level, the browser extension (chrome-gnome-shell) implements extension management itself and so can do things like this. We on the other hand, as well as the official GNOME Extensions app, don't actually manage extensions  but rather communicate with GNOME Shell which handles management on our behalf. This is necessary in order to distribute the app as a flatpak.

So supporting this is very unlikely, although if the situation changes I'd be happy to revisit.
