### ISSUE TITLE
Suggestion: 

### ISSUE THREAD

**Issue by MooWaza** [mjakeman/extension-manager#254]
Sorry if this is the wrong place for suggestions, but this is also an issue I had with using extensions in general so I thought it should be fine. 

Recently, I was trying to make some of my extensions available system-wide so that all profiles could use them, and so that they were updated no matter who was using the PC. Doing this is a huge pain and you run into plenty of permissions issues, so I have a suggestion for the Extension Manager app to make this easier: 
Could we please have a button to make any extension system-wide, and vice versa? Just a simple button that you click it, and it asks for your password (super user is required I think). I doubt it would be very hard to implement, since a script could do it, this would just be much more convenient and elegant. 

Thanks for your time

**Comment by mjakeman** [comment]
It's an interesting idea but I'm not sure Extension Manager is the right place for it.

Extension Manager is really two separate apps in one:
 - It is a management tool, which gives users the ability to manage any extension currently loaded by GNOME Shell (these are sourced from both user and system directories - but extension manager has no knowledge of this).
 - And a browsing tool, which is a wrapper around the public Extensions website API. It's a bit like running the website locally on your computer, except it's written in C and GTK instead of Python and HTML/CSS. When the user asks to install an app, it handles that request and instructs GNOME Shell to "install the extension with this ID".

In both cases, the actual downloading/installing/updating/etc is handled by GNOME Shell itself, except for the system folder, where it is done by the package manager. So if you put a user extension in the systems folder, it would no longer be updated, as Shell assumes the package manager will handle it.

I think if you need this for a small number of users, then Lists (#75) would be a good option. Otherwise for any kind of deployment, it's worth just packaging the extension manually and managing it through the system package manager.

**Comment by MooWaza** [comment]
Thanks for your reply! I was unaware that extensions in the systems folder don't update on their own, I was under the impression is was simply available system-wide and that was all. I'll now go move some extensions back I guess.
