### ISSUE TITLE
[FEATURE REQUEST] Allow overriding extension supported versions on unsupported shells

### ISSUE THREAD

**Issue by orowith2os** [mjakeman/extension-manager#274]
This feature would be useful to run some extensions on experimental shell versions, or just unsupported ones. This would also be locked behind a *very* large red flag that it's unsupported and not to expect support if something breaks.

Mainly asking because I'm using Fedora Rawhide and some shell extensions that I use don't support GNOME 43, despite working just fine.

**Comment by mjakeman** [comment]
Extension Manager already supports this :)

You'll need to manually change this setting via the command line, as flatpak does not let apps modify arbitrary system settings (as it should). However once the option is set, Extension Manager will respect it. You can install unsupported extensions fine as-is.

See here for info: https://github.com/mjakeman/extension-manager#-using-unsupported-extensions

_(Note we can't do this per-extension because GNOME Shell will just overwrite it with the latest stable version whenever it checks for updates)_

**Comment by orowith2os** [comment]
ah, got it.

One such workaround would be using flatpak-spawn to utilize gsettings, but that would be an unneeded hole in the sandbox. Would Extension Manager be able to notify the user of the command if it sees an unsupported extension?

**Comment by mjakeman** [comment]
Given that it's really not recommended, I want to avoid promoting it as a solution in-app. At the same time, it'll definitely go inside the (soon to be written) help manual for discoverability.
