### ISSUE TITLE
[UX] Search Results could have pagination

### ISSUE THREAD

**Issue by lainsce** [mjakeman/extension-manager#275]
If a search term has more than what currently is shown as number of results, the app could show pagination on the bottom of the list (with buttons for back/forward)

**Comment by mjakeman** [comment]
As of #221 we have a button which loads a further ten results (and so on, until there are no results left). This will be part of version 0.4.

I'm not too sold on pagination because it's a bit awkward for mobile/tablet form factors, whereas infinite scrolling feels a bit more 'natural'.

<img width="860" alt="image" src="https://user-images.githubusercontent.com/12368711/192082398-cf66004c-0f93-43ad-906b-797b35e10580.png">

**Comment by lainsce** [comment]
Oh, I went with pagination because I thought the fetching process was deliberately limiting the amount of extensions pulled to not trip requests or something :P

Nice to know that there's a fix coming :)
