### ISSUE TITLE
Error when starting the application from oracle linux 8.7 (gnome 3.32.2)

### ISSUE THREAD

**Issue by extropyst** [mjakeman/extension-manager#318]
### **This window appears:**  
  
  
![Captura de pantalla de 2022-12-06 03-01-11](https://user-images.githubusercontent.com/77421034/205832539-a6ce5c83-ee2a-480d-8f86-b0da837ae37a.png)
  
### **With the following text:**  
  
`Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Shell.Extensions was not provided by any .service files`

**Comment by mjakeman** [comment]
Which package format are you using to run Extension Manager (i.e. flatpak)?

Extension Manager "officially" only supports GNOME 40 and newer, as the extension mechanism is fairly stable on those versions. That being said, it has "best effort" support for some older versions, and I know it works to some degree on GNOME 3.36 too. Unfortunately I have a feeling 3.32 might be a bit _too_ old to reasonably support, especially since it's been EOL'd for a while now.

**Comment by oscfdezdz** [comment]
Extensions app in [Flathub](https://flathub.org/apps/org.gnome.Extensions) specifies support for version GNOME 3.36 or newer, so we have the same limitation.
