### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by wdhaun** [mjakeman/extension-manager#347]
I have a new issue after a new install of Ubuntu 22.04.2 LTS. Here is the error informaion:
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.148" (uid=1000 pid=23432 comm="/snap/gnome-extension-manager/10/usr/bin/extension" label="snap.gnome-extension-manager.gnome-extension-manager (enforce)") interface="org.gnome.Shell.Extensions" member="CheckForUpdates" error name="(unset)" requested_reply="0" destination=":1.149" (uid=1000 pid=23475 comm="/usr/bin/gjs /usr/share/gnome-shell/org.gnome.Shel" label="unconfined")

**Comment by mjakeman** [comment]
Hi, this is a known issue with the snap package. The package is unofficial and not maintained by me (although it will be in the near future).

In the mean time, please use the [official flatpak](https://flathub.org/apps/details/com.mattjakeman.ExtensionManager) package as that has been tested and works on Ubuntu. I know Canonical also packages it in their repos, so that could work too.
