### ISSUE TITLE
Global extensions toggle gets stuck

### ISSUE THREAD

**Issue by Neo-29** [mjakeman/extension-manager#388]
Theme adwaita stock
![image](https://user-images.githubusercontent.com/90937180/236912422-b1836720-cb2b-4340-bb05-07f9c7a16312.png)

something here has to be tweaked

on the picture the extension is on but the icon is strangely not correct

does not happen with the rest of the extensions on

![image](https://user-images.githubusercontent.com/90937180/236913047-c09048db-7a31-4834-a56f-16cd84fcab8d.png)

**Comment by TheEvilSkeleton** [comment]
This happens because we're using `state`:

https://github.com/mjakeman/extension-manager/blob/5e70df4a3be3e1fb7de5721469e849fd9bdf3bda/src/exm-installed-page.c#L274

Instead, we should be using `active`. `state` is used when it's in the _process_ of turning on or off. In this case, it's shown that it's turned on but _in the process of turning off_ (visually, not functionally).
