### ISSUE TITLE
Animated "Smooth" Scrolling on Page Down

### ISSUE THREAD

**Issue by MarjaE2** [mjakeman/extension-manager#435]
**Describe the bug**
If users try to Page Down through the search results, Extension Manager fires animated "smooth" scrolling, even if users have disabled "effects" in the settings.

**System Information:**
 - Fedora 38 T2
 - Extension Manager version 0.4.2
 - Probably Flatpack

**Additional context**
Fedora's Software app doesn't respect this safety setting either.

**Comment by mjakeman** [comment]
Hi, this issue is completely out of my control as flatpak applications can't read system settings (for security reasons).

Since it also affects Software, it'll likely be due to how Fedora has configured flatpak. In theory, this is supposed to work automatically.

I would open an issue on Fedora's bugzilla following these steps: https://docs.fedoraproject.org/en-US/quick-docs/howto-file-a-bug/
