### ISSUE TITLE
Search results broken unless sorting by "recent"

### ISSUE THREAD

**Issue by t3dium** [mjakeman/extension-manager#451]
When sorting by recent, and for e.g searching for `AppIndicator and KStatusNotifierItem Support`, the results are relevant as seen below:

![image](https://github.com/mjakeman/extension-manager/assets/83690012/ca913797-49c5-4fc6-8ce7-a2453536db86)

However when sorting by anything else, the extension results are completely unrelated to the search term:

![image](https://github.com/mjakeman/extension-manager/assets/83690012/a73a0018-eea2-4e88-8f02-6829da4da14b)

I've tried several other search terms as well, and the other sorting options.

**Distro:** fedora workstation
**Installation method:** flatpak
**App version:** 0.4.2

**Comment by zleonov** [comment]
I came here to create this JIRA. Let me add a little more context. First let me say this is a great extension and I use it all the time.

To begin with, a question: How does the Extension Manager implement search functionality? Does the Gnome Extensions website provide an API endpoint? Does the extension completely bypass the Gnome Extensions website?

I ask because on the one hand there are incongruencies between the website search functionality and this extension's search functionality. Yet they are both _broken_ in similar ways.

Specifically: The Gnome Extension website and this extension both provide the following sorting options (assuming you enable unsupported extensions in this extension):

| Gnome Extensions website | Extension Manager | Notes |
| --------------- | --------------- | --------------- |
| Name | Name | Results are identical, not useful |
| Downloads | Downloads | Results are identical, sometimes useful |
| Popularity | Popularity | Results are identical, not useful |
| Relevance | Recent | Results are identical between the _Relevance_ option on the website and the _Recent_ option in this extension. This is the only search option that provides sensible results. |
| Recent | N/A ||

I did a little more comparing and it seems the reason the results for options other than _Relevance_/_Recent_ seem irrelevant is because the search is performed via an OR modifier applied for all the search terms, e.g. if you are searching for _Hide Top Bar_ you'll get results for "Hide" OR "Top" OR "Bar" which are not very useful.

**Comment by Poly2it** [comment]
I am also experiencing this issue.

**Comment by demirdegerli** [comment]
Yes, popularity results should only be shown if there is nothing entered. Recent option should be default for searching.

**Comment by mjakeman** [comment]
This was fixed in v0.4.3 - it should be available just about everywhere.

Please report any further search problems - thanks!
