### ISSUE TITLE
Can " gsettings set org.gnome.shell disable-extension-version-validation “true” " be a toggle option in the app?

### ISSUE THREAD

**Issue by onlyreportingissues** [mjakeman/extension-manager#549]
I think it would be a nice option to have.

**Comment by mjakeman** [comment]
Hi, thanks for the request.

I looked into this a while back and unfortunately it's not possible within the flatpak sandbox due to security reasons. To prevent apps from changing system settings, flatpak does not allow us to read/write gsettings.

So yeah, this is purely a technical limitation for us. If it changes in the future I'm happy to reconsider this.
