### ISSUE TITLE
Hide extension category when empty

### ISSUE THREAD

**Issue by bdaase** [mjakeman/extension-manager#63]
When a category, e.g. system extensions, is empty it should be hidden instead of showing an empty GTKListBox

![image](https://user-images.githubusercontent.com/24682367/150792714-40043d71-82ef-4168-a845-630ac8941e9e.png)

**Comment by mjakeman** [comment]
Yeah, this seems sensible. If there are no extensions across both user and system, we should have a "Install some extensions" splash page.

**Comment by mjakeman** [comment]
Looks like the placeholder text code was accidentally removed in https://github.com/mjakeman/extension-manager/commit/447675b4f54da79bf9ba9f7e18ace58956386dcd. The feature is done, but it'll have to wait for now since I've promised no changes to strings... :/

I'll add it back once the string freeze is over.
