### ISSUE TITLE
GTK critical error

### ISSUE THREAD

**Issue by ndelobel** [mjakeman/extension-manager#709]
**Describe the bug**
When I start the app, I get mutliple GTK critical error resulting in a blank window.
![Screenshot from 2024-09-01 11-01-45](https://github.com/user-attachments/assets/adf5f242-50a1-4fbf-a44c-0a5b2cc5ba5a)

**System Information:**
 - distro: Arch Linux
 - version: 0.5.1
 - package: AUR

**Comment by oscfdezdz** [comment]
This was fixed with https://github.com/mjakeman/extension-manager/pull/675 but has not yet reached a release.

You can use the Flatpak version or build it manually, see [Building From Source](https://github.com/mjakeman/extension-manager?tab=readme-ov-file#building-from-source). Since [extension-manager-git](https://aur.archlinux.org/packages/extension-manager-git) is not up to date.

**Comment by oscfdezdz** [comment]
It seems that GLib and GTK were recently updated in Arch. @bill88t, sorry for the ping, if I remember correctly you maintain the AUR package. Commit 91d1c42a30e12131dc3c5afd8a709e7db2a95b70 should solve the criticals there.

**Comment by oscfdezdz** [comment]
Thank you very much! I'll proceed to close the issue then.
