### ISSUE TITLE
Magic switch in the top bar causes Gnome to hang but its purpose remains unclear

### ISSUE THREAD

**Issue by qux7** [mjakeman/extension-manager#725]
**Describe the bug**
There is a switch in the top bar. It is unclear what it does. I tried it, it caused Gnome to hang for some minutes, but I did not learn what the switch does.

Expected: some information about that switch (a text label, a tool tip, anything)
Actual: I cannot guess what the switch does

**System Information:**
 - Distro: Ubuntu 22.04.3 LTS jammy
 - Extension Manager version: 0.5.1 (reported as 0.3.0 in the "About..." box)
 - Package format: Flatpak

**Additional context**
none

**Comment by oscfdezdz** [comment]
If you recently installed Extension Manager and its version is 0.3.0, you are using [Ubuntu's package](https://packages.ubuntu.com/jammy/gnome-shell-extension-manager) instead of Flatpak.

The switch in the header bar is a global toggle to enable/disable extensions. It is clearer in newer versions, see https://github.com/mjakeman/extension-manager/blob/master/data/screenshot-installed.png.

If the switch hangs the GNOME session, I recommend that you install the latest version from [Flathub ](https://flathub.org/apps/com.mattjakeman.ExtensionManager) and test if you can reproduce the error there.

**Comment by oscfdezdz** [comment]
I am closing this issue as it is fixed in newer versions, feel free to reopen it if you find any problems in those as well.
