### ISSUE TITLE
Search installed extensions

### ISSUE THREAD

**Issue by bordam** [mjakeman/extension-manager#8]
In the official extensions app (since version 40 I think?) you can search through installed extensions. Would be awesome if you could make something similar!

**Comment by mjakeman** [comment]
This shouldn't be too hard to add. We store "local extensions" as a `GListModel`, so something like [`GtkFilterListModel`](https://docs.gtk.org/gtk4/class.FilterListModel.html) should achieve this effect.

We'll need to figure out the UI for it as well. There should be a clear difference between searching installed extensions, and searching online.

**Comment by forteller** [comment]
I came here to ask for this. I think type to search on the list of installed extensions would be the best way to do it. Most of the time when I look at that list I want to open the settings of a specific extension that I know the name of. Being able to just start typing that name right away would save me some precious seconds now spent looking for that extension. 

The UI would make most sense to be just like in Gnome Settings, I think, where a search box slides down from the top when you start searching. Since you're on the Installed tab, not the Browse tab, confusing it with searching online is not a problem, I think.

Thanks!

**Comment by forteller** [comment]
Isn't the way to make the clear difference in search UI between installed and installable (in addition to being on two separate tabs), that the search for installable extensions has an always visible search box, while searching trough installed extensions should just be type to search while in the correct tab, and the search box to slide down from the top of the window, like when searching in Gnome Settings?

![image](https://user-images.githubusercontent.com/343561/196529930-52ea7037-a03a-4a94-9f61-18c55f1d01fb.png)

**Comment by mjakeman** [comment]
As part of #67 we'll be switching to universal search, so the user can just type to search and it will search installed and online extensions at the same time (with installed shown first). I think that's probably the cleanest way to achieve this (and I'd like to avoid two independent search mechanisms).
