### ISSUE TITLE
Compatibility with Yaru Dark and Light theme of Ubuntu

### ISSUE THREAD

**Issue by PaxtonGround** [mjakeman/extension-manager#82]
Is it possible to make the application compatible with the official ubuntu themes?

**Comment by mjakeman** [comment]
For various technical reasons, libadwaita does not support arbitrary theming. We're using a lot of the new libadwaita widgets in this, so unfortunately there's a zero chance of being compatible with Yaru out of the box, at least in the short term. See https://github.com/mjakeman/extension-manager/issues/20#issuecomment-1013117759 for a bit more info about this.

That being said, some users have had success theming `extension-manager`. Have a look at this comment from a recent omgubuntu article: http://disq.us/p/2m38yuk

I'll close this since there's nothing to fix on our end, but the above approach might be worth a try.
